# Generated by Django 6.0.2 on 2026-03-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userss", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_available",
        ),
        migrations.AddField(
            model_name="user",
            name="specialty",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
